apiVersion: v1
kind: Service
metadata:
  name: employee-attrition-service
spec:
  type: LoadBalancer
  selector:
    app: employee-attrition
  ports:
  - protocol: TCP
      port: 80 
      targetPort: 5000