apiVersion: v1
kind: Service
metadata:
  name: employee-attrition-service
spec:
  type: NodePort
  selector:
    app: employee-attrition
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007